### ISSUE TITLE
Error event-loop-stats not found, ignoring event loop metrics...

### ISSUE THREAD

**Issue by thisfardi** [monzersmiledev/youChat-Bot#5]
![image](https://user-images.githubusercontent.com/38723240/144726481-6800c8a8-18bd-4162-a5ac-bd2e22f58753.png)
can u help to fix ?
thanks

**Comment by monzersmiledev** [comment]
Dear @thisfardi

thank you for letting me know about this issue
I'm sorry for the late response
I would like to let you know that the issue caused by express-status-monitor 
there's some issues with this package that I think I'll probably need to fix by myself because the last update of the package was 2 years ago and the issue is you can't disable the event loop metrics!
there is more issues with the package need to be solved and I think that'll be great for me to fix and help with
the package itself use another package named event-loop-stats see:
https://github.com/RafalWilinski/express-status-monitor/blob/master/src/helpers/gather-os-metrics.js
line 9

I uninstalled the package and commented all the code related to it
thank you for your help :)
